name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.0'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Install Angular CLI and GH Pages
        run: npm install -g @angular/cli angular-cli-ghpages
        
      - name: Build
        run: ng build --configuration production --base-href "https://gitlaws.github.io/angular-net-connect/"
        
      - name: Deploy
        run: npx angular-cli-ghpages --dir=dist/angular-net-connect
