name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Set to your default branch

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.0'
      - name: Install Dependencies
        run: npm install
      - name: Install Angular CLI and GH Pages
        run: npm install -g @angular/cli angular-cli-ghpages
      - name: Build
        run: ng build --configuration production --base-href "https://gitlaws.github.io/angular-net-connect/"
      - name: Deploy
        run: npx angular-cli-ghpages --dir=dist/angular-net-connect
